management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: /actuator/refresh
    actuator:
     enabled: true
logging: 
  level:
    com:
      online: INFO
spring:
  h2:
    console:
      settings:
        web-allow-others: true
