management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: /actuator/refresh
    actuator:
     enabled: true
spring:
    h2:
console:
settings:
web-allow-others: true
logging: 
  level:
    com:
      online: INFO
