security:
  basic:
    enabled: false
logging: 
  level:
    com:
      online: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: /actuator/refresh
    actuator:
     enabled: true
